spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/rest-with-spring-boot-and-java-erudio?useTimezone=true&serverTimezone=UTC
        username: root
        password: 02638862045

    jackson:
        default-property-inclusion: non_null

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: false
